In [83]:
import numpy as np


    1. Création de Tableaux :
        ◦ Créez un tableau unidimensionnel avec les entiers de 0 à 9.
        ◦ Créez une matrice 3x3 avec des valeurs comprises entre 0 et 1.

In [84]:
A = np.arange(10)
 
A


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
B = np.random.rand(3,3)
B

array([[0.85173538, 0.66365855, 0.09339139],
       [0.71387972, 0.58003139, 0.26810494],
       [0.89197279, 0.36668942, 0.28421499]])

 2. Opérations Numériques :
        ◦ Multipliez deux tableaux unidimensionnels de même taille.
        ◦ Calculez la moyenne des éléments d'une matrice.

In [86]:
C = np.arange(10)
C

D = C*A
D


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [87]:
np.mean(D)



28.5

  3. Indexation et Découpage :
        ◦ Sélectionnez les éléments pairs d'un tableau unidimensionnel.
        ◦ Découpez une sous-matrice à partir d'une matrice 4x4.²

In [88]:
D % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [89]:
D[D % 2 == 0]

array([ 0,  4, 16, 36, 64])

In [76]:
F = D[0:3]
F

array([0, 1, 4])

  4. Algèbre Linéaire :
        ◦ Créez une matrice identité 3x3.
        ◦ Inversez une matrice 2x2.

In [90]:
B.shape

(3, 3)

In [91]:
G = np.eye(6) #l'identite de matrice

G

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [93]:
matrice_2x2 = np.array([[1, 2], [3, 4]])
matrice_inverse = np.linalg.inv(matrice_2x2)
matrice_inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

    5. Génération de Nombres Aléatoires :
        ◦ Générez un tableau de 10 nombres aléatoires issus d'une distribution normale.
        ◦ Créez une matrice 4x4 de nombres entiers aléatoires entre 1 et 100.

In [94]:
H = np.random.randn(10)
H

array([ 1.89973835,  0.0209429 ,  1.86125969,  0.38415306, -0.15995683,
       -1.03351439,  0.83628447, -1.01560297, -0.17857035, -0.58035722])

In [95]:
I = np.random.randint(1, 101,(4,4))
I

array([[55, 54, 88, 69],
       [16, 65,  4, 82],
       [98, 77, 45, 68],
       [64, 63, 12, 22]])